---
- hosts: all

  gather_facts: yes
  connection: ssh
  vars:
  vars_files:
     - '../../vault.yml'

  tasks:
  - name: Install required packages.
    apt: pkg={{item}} update_cache=no
    with_items:
    - sysstat
    become: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install the DataDog agent.
    shell: DD_API_KEY={{ datadog_api_key }} sh -c "$(curl -L https://raw.githubusercontent.com/DataDog/dd-agent/master/packaging/datadog-agent/source/setup_agent.sh)"
    become: yes
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
