---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: us-east-1
    cidr: 0.0.0.0/0
  tasks:

    # Create AWS Security group Allow HTTP From Public.
    - name: Create AWS Security Group HTTP From Public.
      local_action:
        module: ec2_group
        name: "{{ item.sg_name }}"
        region: "{{ region }}"
        name: http_port_80_public
        description: HTTP From Public
        state: present
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{ cidr }}"
        rules_egress:
          - proto: all
            cidr_ip: "{{ cidr }}"
      register: aws_sg

    # Add Tags to Security Group Allow HTTP From Public.
    - name: Tag Security Group HTTP from public.
      local_action:
        module: ec2_tag
        resource: "{{aws_sg.group_id}}"
        region: "{{ region }}"
        state: present
        tags:
          Name: HTTP_port_80_public
          env: prod
          proto: HTTP
          port: 80
          created_by: Ansible
